title: 영사마 블로그
description: 하루기록
baseurl: ""  # GitHub Pages용 하위 디렉토리
url: "https://blog.younglee.co.kr"
theme: minima
plugins:
  - jekyll-feed
permalink: /:year-:month-:day-:title/
include:
  - _tags


